# Dockerfile
# Use an official Node.js runtime as a parent image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Bundle app source
COPY . .

# Make the service port available
EXPOSE 4001

# Define the command to run the app
CMD [ "node", "index.js" ]